# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
paginate:         5

# Setup
title:            rakeshbs.github.io
description:      'A collection of random code.'
url:              rakeshbs.github.io
baseurl:          /

author:
  name:           'Rakesh'
  url:            https://twitter.com/rakesh_bs

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  gems:           [jekyll-paginate]

